### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by dman777** [devalexqt/topparser#1]
My goal here is just to run one snapshot of top with `-n 1` without doing the `KILL` in `exports.stop`.

```
one@development ~/github/node-api-calls $ node top.js 
/home/one/github/node-api-calls/node_modules/topparser/index.js:4
        var line=_line.replace(RegExp("%","g"),"").split(":")[1].replace(RegExp(" ","g"),"")
                                                                ^

TypeError: Cannot read property 'replace' of undefined
    at parseLine (/home/one/github/node-api-calls/node_modules/topparser/index.js:4:59)
    at Object.parse (/home/one/github/node-api-calls/node_modules/topparser/index.js:42:2)
    at Socket.<anonymous> (/home/one/github/node-api-calls/top.js:6:19)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
one@development ~/github/node-api-calls $ 
```

``` javascript
var topparser=require("topparser");
const spawn = require('child_process').spawn;
const top = spawn('top', ['-b',"-n","1"]);

top.stdout.on('data', function (data) {
  bob = topparser.parse(data.toString(), 5);
  console.log(bob);
});


top.stderr.on('data', function (data) {
  console.log(`stdout: ${data}`);
});
```

```
one@development ~/github/node-api-calls $ cat bob.txt 
top - 22:28:37 up 1 day, 20:25,  2 users,  load average: 0.00, 0.01, 0.05
Tasks:  67 total,   1 running,  66 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.3 us,  0.1 sy,  0.0 ni, 99.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  2051296 total,  1136492 free,    49152 used,   865652 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  1964276 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20   0    4184   1356   1252 S   0.0  0.1   0:02.37 init
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.02 kthreadd
    3 root      20   0       0      0      0 S   0.0  0.0   0:00.06 ksoftirqd/0
    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0H
    6 root      20   0       0      0      0 S   0.0  0.0   0:01.19 kworker/u6:0
    7 root      20   0       0      0      0 S   0.0  0.0   0:01.11 rcu_sched
    8 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_bh
    9 root      rt   0       0      0      0 S   0.0  0.0   0:00.04 migration/0
   10 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 migration/1
   11 root      20   0       0      0      0 S   0.0  0.0   0:00.07 ksoftirqd/1
   13 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/1:0H
   14 root      rt   0       0      0      0 S   0.0  0.0   0:00.04 migration/2
   15 root      20   0       0      0      0 S   0.0  0.0   0:00.14 ksoftirqd/2
   17 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/2:0H
   18 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 khelper
   19 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kdevtmpfs
   20 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 netns
   23 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 perf
  316 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 writeback
  317 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 crypto
  319 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 bioset
  321 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kblockd
  399 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 ata_sff
  419 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 md
  428 root      20   0       0      0      0 S   0.0  0.0   0:04.62 kworker/1:1
  429 root      20   0       0      0      0 S   0.0  0.0   0:00.28 kworker/2:1
  521 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kvm-irqfd-clean
  547 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kswapd0
  621 root      20   0       0      0      0 S   0.0  0.0   0:00.00 fsnotify_mark
  682 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 acpi_thermal_pm
  684 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kworker/u6:2
  729 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_0
  730 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_0
  733 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_1
  734 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_1
  769 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kpsmoused
  811 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 ipv6_addrconf
  823 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 deferwq
  831 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kworker/2:2
  836 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kworker/1:2
  843 root      20   0       0      0      0 S   0.0  0.0   0:00.27 jbd2/vda2-8
  844 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 ext4-rsv-conver
 1051 root      20   0   37172   3076   2348 S   0.0  0.1   0:00.06 systemd-udevd
 1107 root       0 -20       0      0      0 S   0.0  0.0   0:00.01 kworker/0:1H
 1190 root       0 -20       0      0      0 S   0.0  0.0   0:00.06 kworker/1:1H
 1300 root      20   0       0      0      0 S   0.0  0.0   0:00.00 jbd2/vda1-8
 1301 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 ext4-rsv-conver
 1854 root      20   0   30556   2996   2512 S   0.0  0.1   0:00.02 sshd
 1880 root      20   0  120432   2016   1836 S   0.0  0.1   0:00.04 agetty
 1881 root      20   0  120432   1948   1772 S   0.0  0.1   0:00.04 agetty
 1882 root      20   0  120432   1932   1748 S   0.0  0.1   0:00.00 agetty
 1883 root      20   0  120432   2004   1824 S   0.0  0.1   0:00.00 agetty
 1884 root      20   0  120432   1980   1804 S   0.0  0.1   0:00.00 agetty
 1885 root      20   0  120432   1936   1756 S   0.0  0.1   0:00.03 agetty
 1893 root       0 -20       0      0      0 S   0.0  0.0   0:00.02 kworker/2:1H
27514 mongodb   20   0  486136  43780  16128 S   0.0  2.1   5:05.11 mongod
28363 root      20   0   66352   5084   4388 S   0.0  0.2   0:00.01 sshd
28365 one       20   0   99656   4152   3368 S   0.0  0.2   0:00.40 sshd
28370 one       20   0  121936   3748   3208 S   0.0  0.2   0:00.05 bash
28374 root      20   0   66352   4980   4284 S   0.0  0.2   0:00.01 sshd
28376 one       20   0   99656   3964   3184 S   0.0  0.2   0:00.37 sshd
28381 one       20   0  121936   3788   3244 S   0.0  0.2   0:00.07 bash
28559 one       20   0  151156   8460   5452 S   0.0  0.4   0:00.87 vi
28586 root      20   0       0      0      0 S   0.0  0.0   0:00.16 kworker/0:1
28665 root      20   0       0      0      0 S   0.0  0.0   0:00.01 kworker/0:2
28692 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0
28711 one       20   0  123520   2752   2424 R   0.0  0.1   0:00.00 top
```

**Comment by dman777** [comment]
just a side note, I have no issues with using `exports.start` :+1:

**Comment by devalexqt** [comment]
new version
